agent:
  # ---------- AUTH  ----------
  # !!! This helm chart provides two way for passing the personal access token. PLEASE fill only 'pat' or 'patSecret'.
  # 1st way: Personal access token could be passed with 'pat' field.
  pat: ""

  # 2nd way: If a secret that contains personal access token exists in kubernetes, its name and key could be passed with following fields.
  patSecret: ""
  patSecretKey: "pat"
  # ---------- AUTH  ----------

  # Arguments passed to ./start.sh ENTRYPOINT of agent's docker image
  args: []

  # Server / organization url, e.g.: https://dev.azure.com/your-organization-name
  organizationUrl: ""

  # Agent pool name which the build agent is placed into
  pool: "Default"

  # Working directory of agent
  workingDirectory: "_work"

  # Additional environment variables, if you need
  extraEnv: {}
    # ENVNAME: "VALUE"

nameOverride: ""
fullnameOverride: ""
replicaCount: 1

image:
  registry: docker.io
  repository: devops/azure-cd-agent
  pullPolicy: IfNotPresent
  tag: "1.1.0"
  pullSecrets: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

volumes: []
  # - name: dockersock
  #   hostPath:
  #     path: /var/run/docker.sock
volumeMounts: []
  # - name: dockersock
  #   mountPath: "/var/run/docker.sock"

# Additional init containers, e. g. for providing custom themes
extraContainers:
  #  |
  # - name: check-service
  #   image: curlimages/curl
  #   imagePullPolicy: IfNotPresent

serviceAccount:
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}

nodeSelector: {}
tolerations: []
affinity: {}
podLabels: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
